### ISSUE TITLE
Generating valid .mailsignature-file

### ISSUE THREAD

**Issue by danielfriis** [CloudUnder/mac-signature-installer#1]
Super nice with this installer!

One question: How would I generate a valid .mailsignature-file?

I'm looking for a way to just feed it raw HTML.

Thanks

**Comment by Manc** [comment]
Hi @danielfriis, thanks for your feedback. Generating the mailsignature file is (at least currently) not part of this project. You would have to generate MIME email headers such as `Content-Transfer-Encoding: quoted-printable` etc. I did all this in a separate project for a specific project. Maybe I get the chance to add this soon (can't promise).

**Comment by Manc** [comment]
Official version 0.2.0 can now add the necessary MIME headers to the HTML body.
